export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const DELETE_ALL_CUSTOMERS = 'DELETE_ALL_CUSTOMERS';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS';

export const ADD_INVOICE = 'ADD_INVOICE';
export const EDIT_INVOICE = 'EDIT_INVOICE';
export const SET_INVOICES = 'SET_INVOICES';
export const REMOVE_INVOICE = 'REMOVE_INVOICE';
export const DELETE_ALL_INVOICES = 'DELETE_ALL_INVOICES';

export const ADD_INVOICE_ITEM = 'ADD_INVOICE_ITEM';
export const EDIT_INVOICE_ITEM = 'EDIT_INVOICE_ITEM';
export const SET_INVOICE_ITEMS = 'SET_INVOICE_ITEMS';
export const REMOVE_INVOICE_ITEM = 'REMOVE_INVOICE_ITEM';
export const DELETE_ALL_INVOICE_ITEMS = 'DELETE_ALL_INVOICE_ITEMS';

export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_REQUEST = 'RECEIVE_REQUEST';