export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const SET_CUSTOMERS = 'SET_CUSTOMERS';
export const REMOVE_CUSTOMER = 'REMOVE_CUSTOMER';
export const DELETE_ALL_CUSTOMERS = 'DELETE_ALL_CUSTOMERS';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_ALL_PRODUCTS = 'DELETE_ALL_PRODUCTS';

export const SEND_REQUEST = 'SEND_REQUEST';
export const RECEIVE_REQUEST = 'RECEIVE_REQUEST';